function(generate_pack_for_haf)
    # Common properties
    set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Haf main install package")
    set(CPACK_PACKAGE_NAME "HafCore")
    set(CPACK_PACKAGE_VENDOR "Ismael Gonzalez Burgos")
    set(CPACK_PACKAGE_VERSION_MAJOR "1")
    set(CPACK_PACKAGE_VERSION_MINOR "0")
    set(CPACK_PACKAGE_VERSION_PATCH "0")
    set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
    set(CPACK_COMPONENTS_ALL types)
    set(CPACK_COMPONENT_TYPES_GROUP "types")
    if(WINDOWS)
        message("Packaginf haf for Windows")
        set(CPACK_GENERATOR "ZIP")
    else()
        set(CPACK_GENERATOR "DEB")
        set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_VENDOR}")
        set(CPACK_DEBIAN_FILE_NAME "haf.deb")
    endif()
    include(CPack)
endfunction()
